import React, { useState } from "react";
import Head from "next/head";
import useFetch from "../hooks/useFetch";

import * as api from "../lib/api";
import { Post } from "../types/post";
import PostList from "../components/PostList";

export default function Home() {
  const [page, setPage] = useState(0);
  const { posts, isLoaded, hasMore, loadMore } = useFetch();

  const handleLoad = () => {
    setPage((page) => page + 1);
    loadMore({ index: page, items: 10 });
  };

  return (
    <>
      <Head>
        <title>Infinite Scroll Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isLoaded ? <PostList posts={posts} /> : <h1>Loading...</h1>}
      {hasMore ? (
        <button
          style={{
            display: isLoaded ? "block" : "none",
            marginTop: "16px",
            padding: "16px 0",
            borderRadius: "0.5rem",
            backgroundColor: "#c4c4c4",
            fontSize: "1.25rem",
          }}
          onClick={handleLoad}
        >
          Load More...
        </button>
      ) : (
        <h1>沒有更多的貼文了</h1>
      )}
    </>
  );
}

export async function getStaticProps() {
  const posts: Post[] = await api.getPosts();

  return { props: { data: posts } };
}
